### PR TITLE
Redirect from old record URLs with 301 moved permanently

### LINKED ISSUE #45: Restore old URLs
Change routes to match the old URLs like `http://digitalisiertedrucke.de/record/46713`

Depends on #32

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #45

### CODE REVIEW

**Comment by dr0i** [comment]
Checks failed -> reassigning

**Comment by dr0i** [comment]
Why do redirections another way (instead of using apache.conf as we do in all(?!) other cases)?

**Comment by fsteeg** [comment]
For digitalisiertedrucke the apache only provides the proxy, there are no application specific settings in the apache config. To me it feels more self-contained to have all the logic within the application, independent of the proxy. If you'd prefer the other way, I would not object if you implement a 301 redirect on the apache level (note however that the other parts of this pull request are still required, in particular support for IDs without `P` or `D` and the somewhat unrelated `zvdd.hbz.k.de` special case).

**Comment by dr0i** [comment]
I find it more confusing doing things differently, especially when later tracing bugs, but as I have not the time to implement this just take this as a note.
+1 for deploying

**Comment by fsteeg** [comment]
Actually merged, see https://github.com/hbz/digitalisiertedrucke/commits/master

**Pull request closed without merging**
